const ALLOWED_ORIGINS = new Set([
  "https://kyleops.github.io",
  "https://deck-oracle.xyz",
  "http://localhost:3000",
  "http://127.0.0.1:3000"
]);

// Keep this list deliberately narrow. These are the API hosts generated by
// decklistImport.js, not every subdomain owned by each provider.
const ALLOWED_TARGET_HOSTS = new Set([
  "api2.moxfield.com",
  "moxfield.com",
  "www.moxfield.com",
  "archidekt.com",
  "www.archidekt.com"
]);

export function isAllowedOrigin(origin) {
  return typeof origin === "string" && ALLOWED_ORIGINS.has(origin);
}

/**
 * Parse a proxy destination and return a normalized URL only when it is safe.
 * Exact host matching avoids lookalikes such as moxfield.com.evil.example.
 */
export function parseAllowedTarget(targetUrl) {
  if (typeof targetUrl !== "string" || targetUrl.length === 0) return null;

  try {
    const parsed = new URL(targetUrl);
    const hasCredentials = parsed.username.length > 0 || parsed.password.length > 0;
    const hasCustomPort = parsed.port.length > 0;

    if (
      parsed.protocol !== "https:" ||
      hasCredentials ||
      hasCustomPort ||
      !ALLOWED_TARGET_HOSTS.has(parsed.hostname)
    ) {
      return null;
    }

    return parsed;
  } catch {
    return null;
  }
}

function corsHeaders(origin) {
  return {
    "Access-Control-Allow-Origin": origin,
    "Vary": "Origin"
  };
}

const REDIRECT_STATUSES = new Set([301, 302, 303, 307, 308]);
const MAX_REDIRECTS = 2;

/**
 * Follow a small number of redirects without ever leaving the target allowlist.
 * Cloudflare Workers supports manual redirects across older compatibility dates,
 * whereas `redirect: "error"` can throw before making the subrequest.
 */
async function fetchAllowedTarget(target, headers, redirectsRemaining = MAX_REDIRECTS) {
  const response = await fetch(target.href, { headers, redirect: "manual" });
  if (!REDIRECT_STATUSES.has(response.status)) return response;

  const location = response.headers.get("Location");
  if (!location) return response;
  if (redirectsRemaining <= 0) throw new Error("Upstream redirect limit exceeded");

  const redirectTarget = parseAllowedTarget(new URL(location, target.href).href);
  if (!redirectTarget) throw new Error("Blocked upstream redirect outside the provider allowlist");

  return fetchAllowedTarget(redirectTarget, headers, redirectsRemaining - 1);
}

export default {
  async fetch(request, env) {
    const origin = request.headers.get("Origin");
    const originAllowed = isAllowedOrigin(origin);

    // Handle CORS preflight requests
    if (request.method === "OPTIONS") {
      if (!originAllowed) {
        return new Response("Origin not allowed", { status: 403 });
      }

      return new Response(null, {
        headers: {
          ...corsHeaders(origin),
          "Access-Control-Allow-Methods": "GET, OPTIONS",
          "Access-Control-Allow-Headers": "Content-Type",
        },
      });
    }

    // Validate origin for all requests
    if (!originAllowed) {
      return new Response("Origin not allowed", { status: 403 });
    }

    if (request.method !== "GET") {
      return new Response("Method not allowed", {
        status: 405,
        headers: { "Allow": "GET, OPTIONS", ...corsHeaders(origin) }
      });
    }

    const url = new URL(request.url);
    const targetUrl = url.searchParams.get("url");

    if (!targetUrl) {
      return new Response("Missing 'url' query parameter", {
        status: 400,
        headers: corsHeaders(origin)
      });
    }

    const target = parseAllowedTarget(targetUrl);
    if (!target) {
      return new Response("Only Moxfield and Archidekt URLs are allowed", {
        status: 403,
        headers: corsHeaders(origin)
      });
    }

    try {
      // The User Agent is stored in the environment variable MOXFIELD_USER_AGENT
      // This keeps it secure and out of the client-side code.
      const userAgent = String(env?.MOXFIELD_USER_AGENT || "Moxfield-Import-Bot/1.0")
        .replace(/[\r\n]/g, " ")
        .slice(0, 256);
      const response = await fetchAllowedTarget(target, {
        "User-Agent": userAgent,
        "Accept": "application/json"
      });

      const data = await response.text();

      return new Response(data, {
        status: response.status,
        headers: {
          "Content-Type": response.headers.get("Content-Type") || "application/json",
          ...corsHeaders(origin)
        },
      });
    } catch (error) {
      const errorName = error instanceof Error ? error.name : "UnknownError";
      const errorMessage = error instanceof Error ? error.message : String(error);
      console.error(`Deck import proxy request failed: ${errorName}: ${errorMessage}`);
      return new Response(JSON.stringify({ error: "Upstream request failed" }), {
        status: 502,
        headers: {
          "Content-Type": "application/json",
          ...corsHeaders(origin)
        },
      });
    }
  },
};
